### ISSUE TITLE
Woocommerce. Fix warning about incorrectly called id

### ISSUE THREAD

**Issue by IrynaMlshvk** [rulecom/woorule#15]
**Based on the report from customer:**
When installing the plugin and activating it they receive warnings about incorrectly called id. 

**Example 1:**
`
Notice: id anropades felaktigt. Order properties should not be accessed directly. Backtrace: require(‘wp-blog-header.php’), require_once(‘wp-load.php’), require_once(‘wp-config.php’), require_once(‘wp-settings.php’), do_action(‘init’), WP_Hook->do_action, WP_Hook->apply_filters, KCO_Confirmation->confirm_order, kco_confirm_klarna_order, WC_Order->payment_complete, WC_Order->save, WC_Order->status_transition, do_action(‘woocommerce_order_status_changed’), WP_Hook->do_action, WP_Hook->apply_filters, WC_Admin_Settings_Rulemailer::order_status_changed, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Mer information finns i Felsökning i WordPress. (Detta meddelande lades till i version 3.0.) 
`

**Example 2:**
`
Notice: user_id anropades felaktigt. Order properties should not be accessed directly. Backtrace: require(‘wp-blog-header.php’), require_once(‘wp-load.php’), require_once(‘wp-config.php’), require_once(‘wp-settings.php’), do_action(‘init’), WP_Hook->do_action, WP_Hook->apply_filters, KCO_Confirmation->confirm_order, kco_confirm_klarna_order, WC_Order->payment_complete, WC_Order->save, WC_Order->status_transition, do_action(‘woocommerce_order_status_changed’), WP_Hook->do_action, WP_Hook->apply_filters, WC_Admin_Settings_Rulemailer::order_status_changed, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Mer information finns i Felsökning i WordPress. (Detta meddelande lades till i version 3.0.) 
`

We are using incorrect property access in `includes/admin/settings/class-wc-admin-settings-woorule.php` in 345 and 348 lanes:
`$v = get_user_meta($order->user_id, $field->attribute, true)`
and
`$v = get_post_meta($order->id, $field->attribute, true)`

Need to change it to `$order->get_id()` (based on [answer](https://stackoverflow.com/questions/43231684/order-properties-should-not-be-accessed-directly-woocommerce-3-0))

Also look for other places in code where it could be improved

**Comment by dwahlqvist** [comment]
Handled in https://github.com/rulecom/woorule/pull/18

**Comment by alexpalo** [comment]
Fixed in v1.4 release
