### ISSUE TITLE
Incompatibility with Custom Order Numbers for WooCommerce

### ISSUE THREAD

**Issue by Richard-klement** [rulecom/woorule#17]
I found that share plugin shares a function name with the plugin at https://www.tychesoftwares.com/store/premium-plugins/custom-order-numbers-woocommerce/

conflicting function is as below:

/wp-content/plugins/woorule/includes/class-wc-woorule.php
function name was:
action_links on lines 188 and 204

Including namespacing would be the best fix here

**Comment by joisak** [comment]
Is there a fix to activate both?

**Comment by Richard-klement** [comment]
My hotfix was to rename the action_links function to woorule_actionlinks which worked just fine but as I say, best option would be namespacing the plugin.

**Comment by neevalex** [comment]
Hi! Fix is scheduled.

**Comment by dwahlqvist** [comment]
@Richard-klement @joisak we (Rule) have assigned this to a developer and an namespacing update is planned, expected delivery in the coming weeks.

**Comment by dwahlqvist** [comment]
@Richard-klement @joisak there's now a PR for this fix https://github.com/rulecom/woorule/pull/18/files. 
We will need some more time for review, test and release of the fix. Depending on how eager you are, you can use the feature branch in the PR, or wait for our stable release

**Comment by alexpalo** [comment]
Fixed in 1.4 release.
