### ISSUE TITLE
Opt-in signup for newsletter

### ISSUE THREAD

**Issue by AlexBeredd** [rulecom/woorule#19]
I would like to request a pre-checked option box for the newsletter and offers in the checkout.
This request is for websites that use Woocommerce. 

In short I want the check-box for the optional newsletter subscription to be pre-checked. This means that if the customer doesn't want to subscribe to our  newsletter, it has to be an active action.

**Comment by alexpalo** [comment]
Hello @AlexBeredd, and sorry for the delay!

We can consider this feature for a future release, however this is not immediately on our roadmap.

For now you can easily customize the newsletter checkbox in the frontend to be checked by default in the Plugin Editor on the Admin Panel. 

Hope this helps!
