### ISSUE TITLE
Each WooCommerce category should create a new custom field option in Rule

### ISSUE THREAD

**Issue by dwahlqvist** [rulecom/woorule#3]
Today if a product is tagged with multiple categories, these get "merged" into on custom field option in Rule. Example: "Almea, RULE XLASH, Xlash" is 3 categories in WooCommerce but 1 custom field option in Rule. This makes it difficult to use for segmentation

**Comment by IrynaMlshvk** [comment]
@dwahlqvist did I understand it incorrectly, but as I see from logs, we already pass categories as multiple options, not a single string
![image](https://user-images.githubusercontent.com/34026400/70335790-a69d5300-1850-11ea-87a8-71f23b8b9456.png)

And if check field options in DB thay are also separated
![image](https://user-images.githubusercontent.com/34026400/70335828-b9178c80-1850-11ea-804b-91b31e8ec8ce.png)


We just display them in UI separated by ','
![image](https://user-images.githubusercontent.com/34026400/70335906-e2d0b380-1850-11ea-9467-0d2853c8880c.png)

**Comment by dwahlqvist** [comment]
@IrynaMlshvk Ok, I actually didn't research it deep, I just reacted to the bugsnag. I can see it keep coming, latest was today https://rulemailer.slack.com/archives/C02M3T4PP/p1575634632349200.

Does the bugsnag tell you more? Can we discard it or is there something to fix there?

**Comment by IrynaMlshvk** [comment]
@dwahlqvist thanks, found what the issue was. Didnt consider this bugsnag before
