### ISSUE TITLE
Add Cart URL to Cart in Progress

### ISSUE THREAD

**Issue by alexpalo** [rulecom/woorule#39]
When cart data is sent to Rule we should also include the URL to the cart.

Perhaps `wc_get_cart_url()` would be the appropriate function: 
https://woocommerce.wp-a2z.org/oik_api/wc_get_cart_url/

**Comment by webcodist** [comment]
@alexpalo WooCommerce by default do not have functionality to open a user specific cart page with products added by this user. WooCommerce have permalink https://site.com/cart/ for cart page, but content will be different for each user.
